plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - style_transfer_methods.md
  - style_transfer_data.md
  - style_transfer_demo.md
theme: jekyll-theme-minimal
