
include:
  - style_transfer_methods.md
  - style_transfer_data.md
  - style_transfer_demo.md
  - CONTRIBUTING.md
  - README.md
remote_theme: pages-themes/midnight@v0.2.0
plugins:
  - jekyll-remote-theme 
title: ArtCV-Object Detection in Artistic Images
